version: "3.8"

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    volumes:
      - postgres:/data/postgres
      - "./sql/init.sql:/docker-entrypoint-initdb.d/init.sql"
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "root@root.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    ports:
      - "80:80"
    depends_on:
      - postgres
    links:
      - "postgres:pgsql-server"
    networks:
      - postgres

  python:
    container_name: srv_python
    build: .
    restart: "no"
    depends_on:
      - postgres
    networks:
      - postgres

networks:
  postgres:
    external: false
    name: postgres
    driver: bridge

volumes:
  postgres:


