version: "3.8"
services:

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    volumes:
      - "./sql/init.sql:/docker-entrypoint-initdb.d/init.sql"
 
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "root@root.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    ports:
      - "80:80"
    depends_on:
      - postgres
    links:
      - "postgres:pgsql-server"
    
  python:
    build: .
    volumes:
       - data:/app/python/
    links:
      - "postgres:bbdd_postgresql"
    depends_on:
      - pgadmin
   

volumes:
  data:
